name: DAILY PAYMENTS

on:
  schedule:
    # Run daily at 00:30 UTC (adjust timezone as needed)
    - cron: '30 0 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-daily-payments:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pandas pandas-gbq \
            google-cloud-bigquery google-cloud-bigquery-storage \
            google-cloud-storage \
            pyarrow db-dtypes
                  
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_TELCO_METRICS }}
      
      - name: Run Daily Payments script
        run: |
          python .github/workflows/GCP_Telco_Metrics/Daily_Payments.py
